package pabstsoftware.tools.poi;

/*
 * Hauptfenster.java
 *
 * Created on 30. Mai 2008, 08:29
 */

import org.apache.poi.hssf.util.CellReference;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import java.io.File;
import java.io.FileInputStream;

/**
 * Klasse zur Erzeugung des Programmfensters
 * @author  Jean-Rene Thies
 */
public class Hauptfenster extends javax.swing.JFrame {

    FileInputStream fis = null;
    XSSFWorkbook wb = null;

    /**
     * Konstruktor des Hauptfensters
     */
    public Hauptfenster() {
        initComponents();
    }

    /**
     * Arbeitsblätter in der gewählten Exceldatei ermitteln und in Klappmenü übertragen
     * @param path Dateipfad zur Exceldatei
     */
    private void getWorksheets(String path) {
        try {
            fis = new FileInputStream(path);
            wb = new XSSFWorkbook(fis);
            int sheetcount = wb.getNumberOfSheets();
            System.out.println(sheetcount);
            for (int i = 0; i < sheetcount; i++) {
                String sheetname = wb.getSheetName(i);
                comboArbeitsblatt.addItem(sheetname);
                System.out.println(sheetname);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code"&gt;                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFile = new javax.swing.JTextField();
        btnFile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboArbeitsblatt = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtFeld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFormel = new javax.swing.JTextArea();
        btnQuit = new javax.swing.JButton();
        btnFormel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POI Formel Finder");

        jLabel1.setText("Pfad zur Excel-Datei:");

        btnFile.setText("Durchsuchen...");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        jLabel2.setText("Arbeitsblatt:");

        jLabel3.setText("Tabellenfeld (z.B. A1)");

        txtFeld.setText("A1");

        jLabel4.setText("Formel:");

        txtFormel.setColumns(20);
        txtFormel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtFormel.setRows(5);
        jScrollPane1.setViewportView(txtFormel);

        btnQuit.setText("Beenden");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        btnFormel.setText("Formel ermitteln");
        btnFormel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createSequentialGroup()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                        .add(jLabel4)
                                                        .add(jLabel3)
                                                        .add(jLabel2)
                                                        .add(jLabel1))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(comboArbeitsblatt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .add(txtFeld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                                                        .add(txtFile, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, btnFormel))
                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(btnFile))))
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, btnQuit))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jLabel1)
                                        .add(btnFile)
                                        .add(txtFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jLabel2)
                                        .add(comboArbeitsblatt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jLabel3)
                                        .add(txtFeld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(btnFormel)
                                .add(11, 11, 11)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel4)
                                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                                .add(btnQuit)
                                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-500)/2, (screenSize.height-300)/2, 500, 300);
    }// </editor-fold&gt;                        

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                return f.isDirectory() ||
                        f.getName().toLowerCase().endsWith(".xls");
            }

            @Override
            public String getDescription() {
                return "Excel-Dateien (*.xls)";
            }
        });

        int state = fc.showOpenDialog(null);
        if (state == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String path = file.getPath();
            txtFile.setText(path);
            getWorksheets(path);
        }
    }

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void btnFormelActionPerformed(java.awt.event.ActionEvent evt) {
        int index = wb.getSheetIndex(comboArbeitsblatt.getSelectedItem().toString());
        Sheet sheet = wb.getSheetAt(index);
        CellReference cellReference = new CellReference(txtFeld.getText());
        Row row = sheet.getRow(cellReference.getRow());
        Cell cell = row.getCell(cellReference.getCol());
        txtFormel.setText(cell.getCellFormula());
    }

    /**
     * @param args command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            @SuppressWarnings("static-access")
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    Hauptfenster hauptfenster = new Hauptfenster();
                    hauptfenster.setDefaultLookAndFeelDecorated(true);
                    hauptfenster.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify                    
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnFormel;
    private javax.swing.JButton btnQuit;
    private javax.swing.JComboBox comboArbeitsblatt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFeld;
    private javax.swing.JTextField txtFile;
    private javax.swing.JTextArea txtFormel;
    // End of variables declaration                  
}